[package]
name = "libllama"
version = "0.1.0"
authors = ["archshift <gh@archshift.com>"]

[dependencies]
bitutils = "2.0"
derive-error = "0.0.4"
indextree = "1.0"
json = "0.11"
log = "0.3"
mio = "0.6"
openssl = "0.10"
parking_lot = "0.4"
arraydeque = "0.4"

[features]
trace_instructions = []
